[package]
name = "puzzle_solver"
version = "0.1.0"
edition = "2021"

[lib]
name = "puzzle_solver"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
fastrand = "2.0"
rayon = "1.10"
indicatif = "0.17"